inherit_gem:
  rubocop-rails-omakase: rubocop.yml

plugins:
  - rubocop-capybara
  - rubocop-rails
  - rubocop-yard
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.4
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'bin/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'doc/**/*'
    - 'docs/**/*'
    - '.git/**/*'
    - 'storage/**/*'
    - db/schema*.rb
    - db/migrate/*.rb

Style/StringLiterals:
  EnforcedStyle: single_quotes

Metrics/BlockLength:
  Exclude:
    - config/environments/*
    - db/*schema.rb

Metrics/MethodLength:
    Max: 20 # Allows methods up to 20 lines
    CountComments: false
    CountAsOne: ['array', 'hash', 'heredoc', 'method_call']
    AllowedMethods:
      - context
      - describe
      - it
