inherit_from: .rubocop_todo.yml

AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'bin/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'doc/**/*'
    - 'docs/**/*'
    - '.git/**/*'
    - 'storage/**/*'
    - db/schema.rb

plugins:
  - rubocop-capybara
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
